apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-django-deployment
  namespace: django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: djano-app
        image: anilrajrimal/django-crud:latest
        ports:
        - containerPort: 8000
